In [2]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [4]:
I = np.eye(3)
x = np.reshape(np.arange(9), (3, 3))
y = np.array([1, 2, 3])



In [5]:
portfolio = np.array([[4, 3],[2.5,3],[8,1.1]])
portfolioBetter = np.array([[4,2.5,8],[3,5,1.1]])
x=portfolioBetter[0]
y = portfolioBetter[1]

print(x@y)

33.3


In [17]:
test = np.ones((4,4))
print(test * 2)
test[0] = test[0] * 2
test[0:, 0] = 3

print(test)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 2. 2. 2.]
 [3. 1. 1. 1.]
 [3. 1. 1. 1.]
 [3. 1. 1. 1.]]


In [23]:
x1 = np.reshape(np.arange(6), (3, 2))
x2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
x3 = np.array([[2, 5, 2], [1, 2, 1]])
x4 = np.ones((2, 3))

y1 = np.array([1, 2, 3])
y2 = np.array([0.5, 0.5])

print(np.dot(x1, x4))



[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [98]:
def productionMatrix(year, production, productionDiscount, npvRate):
    prodMatrix =  np.array([
        ((1-productionDiscount)**(year - 1))*(production) * 1/((1 + npvRate) ** (year-1))

        for year in np.arange(1, year + 1)
    ])
    return prodMatrix

print(np.size((productionMatrix(20,5,0.2,0.05))))


20


In [99]:
years = 20

rateA = 0.2
productionA = 5

productionB = 2
rateB = 0.1

discount = 0.05


print(np.sum(productionMatrix(years, productionA, rateA, discount)) + np.sum(productionMatrix(years, productionB, rateB, discount)))

34.2672564874775
