In [1]:
import numpy as np


In [2]:
x_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x_2d)

print(x_2d[-1,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [3]:
x_3d_list = [[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
x_3d = np.array(x_3d_list)
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print(x.dtype)


(2, 3)
int32


In [5]:
x = np.ones((2, 2))
print("x = ", x)
print("2 + x = ", 2 + x)
print("2 - x = ", 2 - x)
print("2 * x = ", 2 * x)
print("x / 2 = ", x / 2)


x =  [[1. 1.]
 [1. 1.]]
2 + x =  [[3. 3.]
 [3. 3.]]
2 - x =  [[1. 1.]
 [1. 1.]]
2 * x =  [[2. 2.]
 [2. 2.]]
x / 2 =  [[0.5 0.5]
 [0.5 0.5]]


In [6]:
x = np.array([[1.0, 2.0], [3.0, 4.0]])
y = np.ones((2, 2))
print("x = ", x)
print("y = ", y)
print("x + y = ", x + y)
print("x - y", x - y)
print("(elementwise) x * y = ", x * y)
print("(elementwise) x / y = ", x / y)

x =  [[1. 2.]
 [3. 4.]]
y =  [[1. 1.]
 [1. 1.]]
x + y =  [[2. 3.]
 [4. 5.]]
x - y [[0. 1.]
 [2. 3.]]
(elementwise) x * y =  [[1. 2.]
 [3. 4.]]
(elementwise) x / y =  [[1. 2.]
 [3. 4.]]


In [7]:
newArr = list(x_2d[1,1: ])
newArr = np.array((newArr, np.array(newArr)*10))
newArr

array([[ 5,  6],
       [50, 60]])

In [8]:
i = 0.03
M = 100
C = 5

def f(terms, i, cost, m):
    final = ((cost*(1-(1+i)**-terms))/i) + (m*(1+i)**-terms)
    return final

def bondPrice(terms, i, cost, m):
    
    termArr = np.arange(1, terms+1)
    f_vec = np.vectorize(f)
    return f_vec(termArr, i, cost, m)

